tasks:
  - init: yarn install && yarn run build
    command: yarn run start
ports:
  - port: 3000
vscode:
  extensions:
    - Elmtooling.elm-ls-vscode
    - hbenl.test-adapter-converter
    - hbenl.vscode-test-explorer
